### ISSUE TITLE
missing 0.0.1 tag

### ISSUE THREAD

**Issue by warner** [Agoric/marshal#6]
We've got a `0.0.1` release up on NPM, but there's no git tag in this repo to match.

**Comment by katelynsills** [comment]
I added a tag to the appropriate commit here: https://github.com/Agoric/marshal/releases/tag/v0.0.1

I was wondering, what do you think about having a file in https://github.com/Agoric/new-repo that has all of the steps for publishing to npm? I had missed this step earlier.

**Comment by warner** [comment]
Thanks!

Yeah, probably a good idea. SES has a `README-developent.md`, and SwingSet has a `CONTRIBUTING.md`. Maybe we merge those, update it, and make it a standard practice.

The nominal release process is to edit a NEWS.md (enumerating any user-visible changes), then run `npm release (patch | minor | major)`, which does everything for you (modify the version strings in `package.json` and `package-lock.json`, commit with a comment about the new version number, tag the commit, run `npm pack`, run `npm publish`, update to a new post-release version string, commit with that string, and push everything).

In practice I do things differently, because of some personal choices about my dev environment, but we should document the idealized commands anyways.

**Comment by katelynsills** [comment]
Added tag and also added this text as an issue in new-repo

**Comment by warner** [comment]
in the old repo. this was marshal issue 6
